package_update: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli

# https://kind.sigs.k8s.io/docs/user/quick-start/#installation
runcmd:
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers kubelabadmin ubuntu' /etc/ssh/sshd_config
  - /etc/init.d/ssh restart
  # - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
  # - chmod +x ./kind
  # - sudo mv ./kind /usr/local/bin

users:
    - default
    - name: kubelabadmin
      plain_text_passwd: 123456
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      groups: users,docker
      lock_passwd: false
      ssh_pwauth: true
      chpasswd: { expire: false }

  
# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]