---
  # Creates vmadmin keypair that will be used to log into the Multipass VMs
  # and the cloud-init file use when create the VMs.
  # Deletes any existing keys and cloud-init file.
  # - name: Delete any existing public and private keys
  #   file:
  #     path: "{{ item }}"
  #     state: absent
  #   with_items:
  #     - user_key
  #     - user_key.pub

  - name: Example from an Ansible Playbook
    win_ping:

  - name: Getting public key
    delegate_to: localhost
    set_fact:
      public_key: "cat {{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

  - name: Create cloud-init file inserting the public key
    win_template:
      src: kubelab-cloud-init.yaml
      dest: "C:/Users/{{ ansible_user }}/kubelab-cloud-init.yaml"
    # vars:
    #   public_key: "{{ pub_key }}"

  - name: Create new VM
    win_shell: "multipass launch --name kubelab --cloud-init C:/Users/{{ ansible_user }}/kubelab-cloud-init.yaml --cpus {{ kind_cluster_vm_cpus }} --mem {{ kind_cluster_vm_mem }} --disk {{ kind_cluster_vm_disk }} --network '{{ kind_cluster_vm_network }}'"
    

  - name: Example from an Ansible Playbook
    win_ping: