---
  # Creates vmadmin keypair that will be used to log into the Multipass VMs
  # and the cloud-init file use when create the VMs.
  # Deletes any existing keys and cloud-init file.
  # - name: Delete any existing public and private keys
  #   file:
  #     path: "{{ item }}"
  #     state: absent
  #   with_items:
  #     - user_key
  #     - user_key.pub
  - name: Create cloud-init file inserting the public key
    template:
      src: cloud-config.yml
      dest: cloud-init.yaml
    delegate_to: localhost
    vars:
      public_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

  - name: Create new VM
    shell: multipass launch --name kubelab --cloud-init cloud-init.yaml --cpus {{ kind_cluster_vm_cpus }} --mem {{ kind_cluster_vm_mem }} --disk {{ kind_cluster_vm_disk }} --network {{ kind_cluster_vm_network }}
    

  - name: Example from an Ansible Playbook
    ping: