---

  - hosts: host-machine
    vars_prompt:
      - name: ansible_user
        prompt: Username
        private: no      
      - name: ansible_password
        prompt: Password
        private: yes
    roles:
      - kubelab-vm


  # - hosts: kubelab-vm
  #   roles:
  #     - kubelab-vm