---

  - name: Install Python dependencies
    become: true
    apt:
      update_cache: yes
      state: latest
      name: python3-pip

  - name: Install 'Docker SDK for Python'
    pip:
      name: docker

  - name: "Check if kind-cluster already exists"
    docker_container_info:
      name: "kind-cluster"
    register: cluster_check_result

  - name: Create KinD Config dir
    become: true
    file:
      state: directory
      name: "/opt/kind"

  - name: Create KinD Config
    become: true
    template:
      src: "opt/kind/kind-cluster.yml"
      dest: "/opt/kind/kind-cluster.yml"
      mode: "755"

  - name: "Start KinD Cluster"
    command:
      argv:
        - kind
        - create
        - cluster
        - --name=kind-cluster
        - --config=/opt/kind/kind-cluster.yml
    register: kind_cluster_result
    when: (not cluster_check_result.exists)